config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :reminders

  resources :notifications

  resources :users

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div>
  <h1>About</h1>
  <p>A simple rails app for dispatching reminders. Based off the Rails tutorial by Michael Hartl.</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div>
  <h1>Contact</h1>
  <p>
    Ben made this app. You should already know how to contact him.
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div>
  <h1>Help</h1>
  <p>This is the help page, but it isn't very helpful.</p>  
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div>
  <h1>Exotemporalis</h1>
</div>
<br>
<%= link_to "Users", users_path, class: "btn btn-lg btn-default" %>
<%= link_to "Reminders", reminders_path, class: "btn btn-lg btn-default" %>
<%= link_to "Notifications", notifications_path, class: "btn btn-lg btn-default" %>
<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>