config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :reminders

  resources :notifications

  resources :users

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :user
  has_many :notifications
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:user_id, :title, :text, :recurring, :recurrence_period, :trigger_at)
    end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_field :text, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :recurrence_period %><br>
    <%= f.number_field :recurrence_period, class: "form-control" %>
  </div>
  <div class="checkbox">
    <%= f.label :recurring do %>
      <%= f.check_box :recurring %>
      Recurring
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :trigger_at %><br>
    <%= f.datetime_select :trigger_at, class: "form-control" %>
  </div>
  <div class="actions">
    <%= link_to 'Back', :back, class: "btn btn-default" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<% provide(:title, 'Edit Reminder') %>
<div>
  <h1>Edit Reminder</h1>
  <%= render 'form' %>
</div>

app/views/reminders/index.html.erb
<div>
  <h1>Listing reminders</h1>
  <br>
  <table class="table table-hover table-condensed table-responsive">
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Recurring</th>
        <th>Period</th>
        <th>Trigger at</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @reminders.each do |reminder| %>
        <tr>
          <td><%= link_to "#{reminder.user.name}", user_path(reminder.user) %></td>
          <td><%= reminder.title %></td>
          <td><%= reminder.recurring %></td>
          <td><%= reminder.recurrence_period %></td>
          <td><%= reminder.trigger_at.to_formatted_s(:short)  %></td>
          <td><%= link_to 'Show', reminder %></td>
          <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
          <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Reminder', new_reminder_path %>
</div>

app/views/reminders/new.html.erb
<% provide(:title, 'New Reminder') %>
<div>
  <h1>New Reminder</h1>
  <%= render 'form' %>
</div>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reminder.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @reminder.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @reminder.text %>
</p>

<p>
  <strong>Recurring:</strong>
  <%= @reminder.recurring %>
</p>

<p>
  <strong>Recurrence Period:</strong>
  <%= @reminder.recurrence_period %>
</p>

<p>
  <strong>Trigger at:</strong>
  <%= @reminder.trigger_at %>
</p>

<%= link_to 'Back', reminders_path, class: "btn btn-default" %>
<%= link_to 'Edit', edit_reminder_path(@reminder), class: "btn btn-primary" %>