config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :reminders

  resources :notifications

  resources :users

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :reminder

  def user
    return self.reminder.nil? ? nil : self.reminder.user
  end

  def user_id
    return self.user.id
  end

  def dispatch
    unless self.dispatched
      NotificationMailer.notification_email(self).deliver
      self.update(dispatched: true)
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html do
          redirect_to @notification
          flash['alert-success'] = 'Notification was successfully created.'
        end
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html do
          redirect_to @notification
          flash['alert-success'] = 'Notification was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html do 
        redirect_to notifications_url
        flash['alert-success'] = 'Notification was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :reminder_id, :text_content, :dispatched, :trigger_at)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :reminder_id %><br>
    <%= f.number_field :reminder_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_field :text, class: "form-control" %>
  </div>
  <div class="checkbox">
    <%= f.label :dispatched do %>
      <%= f.check_box :dispatched %>
      Dispatched
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :trigger_at %><br>
    <%= f.datetime_select :trigger_at, class: "form-control" %>
  </div>
  <div class="actions">
    <%= link_to 'Back', :back, class: "btn btn-default" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<% provide(:title, 'Edit Notification') %>
<div>
  <h1>Edit Notification</h1>
  <%= render 'form' %>
</div>

app/views/notifications/index.html.erb
<div>
  <h1>Listing notifications</h1>
  <br>
  <table class="table table-hover table-condensed table-responsive">
    <thead>
      <tr>
        <th>User</th>
        <th>Reminder</th>
        <th>Title</th>
        <th>Dispatched</th>
        <th>Trigger at</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @notifications.each do |notification| %>
        <tr>
          <td><%= link_to "#{notification.user.name}", user_path(notification.user) if notification.user %></td>
          <td><%= link_to "#{notification.reminder.title}", reminder_path(notification.reminder) if notification.reminder %></td>
          <td><%= notification.title %></td>
          <td><%= notification.dispatched %></td>
          <td><%= notification.trigger_at.to_formatted_s(:short)  %></td>
          <td><%= link_to 'Show', notification %></td>
          <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
          <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Notification', new_notification_path %>
</div>

app/views/notifications/new.html.erb
<% provide(:title, 'New Notification') %>
<div>
  <h1>New Notification</h1>
  <%= render 'form' %>
</div>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user.name %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @notification.reminder_id %>
</p>

<p>
  <strong>Text content:</strong>
  <%= @notification.text %>
</p>

<p>
  <strong>Dispatched:</strong>
  <%= @notification.dispatched %>
</p>

<p>
  <strong>Trigger at:</strong>
  <%= @notification.trigger_at %>
</p>

<%= link_to 'Back', :back, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_notification_path(@notification), class: 'btn btn-primary' %>